### ISSUE TITLE
Exposed API key

### ISSUE THREAD

**Issue by fancifulcrow** [Joinedthedev/random-gif-generator#1]
First of all, well done on the project. However, there is a glaring issue I want to draw your attention to. 

Your API key is exposed, meaning anyone can use it, and if it was billed, you could end up being charged excessively. When making public code, it is best to ensure that your API keys is not shown in the source code. 

https://www.woubuc.be/blog/post/how-to-use-api-keys-in-client-side-javascript/
https://www.freecodecamp.org/news/how-to-use-environment-variables-in-vanillajs/
https://stackoverflow.com/questions/44342276/how-to-push-code-to-github-hiding-the-api-keys
https://stackoverflow.com/questions/61591049/how-to-add-api-keys-in-vanilla-javascript-with-env-file

The above links would give you a brief description of how to solve it. Please do note that hiding you API key in your repository is different from hiding it in your deployment. You will understand more when reading the links but still research more on this. Once you remove it, regenerate the key since one can still go through your commits. 

Again, well done on the work.
Thank you.

**Comment by Joinedthedev** [comment]
Hey ! Thanks for the warning. I'm aware that the API key is exposed.
This is a free, public api ,so I am in no way, shape or form paying for
this. In the course im taking (TOP) I actually learned about exposing and
hiding API keys. There is generally no risk here since I'm not paying for
it, and it's something anyone can get by just signing up on giphy. Once
again, thanks for the warning. Appreciate it brother!
